== Getting Started

1. Add the following dependency to .build.gradle:

Logback version 1.4.x:
```groovy
implementation 'io.github.virtualdogbert:logback-groovy-config:1.14.4'
```

Logback version 1.3.x:
```groovy
implementation 'io.github.virtualdogbert:logback-groovy-config:1.13.4'
```

Logback version 1.2.x:
```groovy
implementation 'io.github.virtualdogbert:logback-groovy-config:1.12.4'
```

Add a `logback.groovy` file to your resources(e.g. grails-app/config, src/main/resources) using the Groovy DSL. The file name was defaulted
to `logback-config.groovy` in 1.12.1 but was rolled back to `logback.groovy` because newer versions of logback shouldn't throw and exception.
However, you can be the config file name to anything you want. To change the file name you can use the system property: `logback.config.file`
or the environment variable: `LOGBACK_CONFIG_FILE`

You can provide an external config file by setting the VM property `logback.config.external.file`  or the environment property
`LOGBACK_CONFIG_EXTERNAL_FILE`. The external file if provided will take president over the config in the resource.

Depending on the environment external files might make sense, although an alternative is to have environment variables in your internal
config that can control aspects of your logging.