== Version History
* 1.14.4, 1.13.4, 1.12.4
** Adding missing DSL element, adding some more default imports and making the defaults always apply, and are just added on to, rather than overwritten with the `logbackCompiler.groovy`
* 1.14.3, 1.13.3, 1.12.3
** Adding on to default to make the default a little nicer.
* 1.14.2, 1.13.2, 1.12.2
** Found that the DSL methods are "added" to Object, because the dynamic nature of the runtime DSL. So I added on to the ScriptExpressionChecker
accounting for that. I also updated the default config explaining the config of the ScriptExpressionChecker asking if there is a missing DSL method to submit a bug report.
* 1.14.1, 1.13.1, 1.12.1
** Found an issue in #4 where the ScriptExpressionChecker was being overzealous on method calls from objects that has sub objectExpressions
that had types. So I loosened that up, and check for System and String types under the object type, and those have  a restricted set of methods
that they can call.
** Upgraded to versions 1.4.6, 1.3.6, and 1.2.12 for logback versions
** 1.2.12 is being release because there are still a lot of popular projects still using the old version(updated recently).
With this version the config file will be name logback-config.groovy,
because at this point logback will error if you have a logback.groovy.
* 1.14.0
** Upgrading to Logback 1.4.5
* 1.13.0
** Upgrading to Logback 1.3.5
** Changing default filename back to `logback.groovy`
** removing JMX config because it was removed from 1.3.5 because of potential vulnerability
* 1.0
** Initial Release


